update
upgrade

install caskroom/cask/brew-cask

install zsh
install tmux reattach-to-user-namespace
install htop-osx

install nvm
install pyenv

install dnsmasq

install git
install git-extras
install git-flow
install gist

install shellcheck

tap theory/sqitch
install sqitch_pg
